Nest.js 框架默认有自己的错误响应内容，但是很多时候，我们需要自己的响应内容。

- 在`src`目录下创建`httpExeception.ts`文件，进行全局拦截配置

```TS
import {
  ExceptionFilter,
  Catch,
  HttpException,
  ArgumentsHost,
} from '@nestjs/common';
import { timeYMD } from './utils/utils';

@Catch(HttpException)
export class HttpExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse();
    const request = ctx.getRequest();
    const status = exception.getStatus();
    const errResponse: any = exception.getResponse();
    let message = exception.message;
    if (errResponse && errResponse.message) {
      message = errResponse.message;
    }
    if (Array.isArray(message)) {
      message = message.join(',');
    }
    const errorInfo = {
      time: timeYMD(), // 当前时间
      status: 'error',
      status_code: status,
      method: request.method,
      url: request.originalUrl,
      errorMessage: message,
    };
    // 控制台打印错误信息
    console.log(`${JSON.stringify(errorInfo)}`);
    // 错误响应格式
    const errorResponse = {
      status: 'error',
      success: false,
      errorMessage: message,
    };
    if (status !== 401 && status !== 404) {
      response.status(200);
    } else {
      response.status(status);
    }
    response.send(errorResponse);
  }
}

```

- 然后在`main.ts`文件中进行全局挂载即可

```TS
import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { HttpExceptionFilter } from './httpException';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  // 路由前缀
  app.setGlobalPrefix('/api/v1');
  // 使用DTO验证
  app.useGlobalPipes(new ValidationPipe());
  // 全局错误过滤器使用
  app.useGlobalFilters(new HttpExceptionFilter());
  await app.listen(3000);
}
bootstrap();

```
